=== advaithrrajesh/labb3/lab 3/college1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="canteenman">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="canteen" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="cid">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:pattern value="[0-9]"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="name">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="([a-zA-Z])*"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element type="xs:string" name="place"/>
              <xs:element  name="custid">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="([a-zA-Z0-9])*"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element type="xs:integer" name="stalllid"/>
              <xs:element type="xs:integer" name="inputid"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== advaithrrajesh/labb3/lab 3/college.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="college2.xsl" type="text/xsl"?>
<canteenman xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="college1.xsd">
	<canteen>
		<cid>1</cid>
		<name>Mingos</name>
		<place>Block1</place>
		<custid>null</custid>
		<stallid>null</stallid>
		<inputid>1</inputid>
	</canteen>
	<canteen>
		<cid>1</cid>
		<name>Mingos</name>
		<place>Block1</place>
		<custid>1</custid>
		<stallid>null</stallid>
		<inputid>2</inputid>
	</canteen>
	<canteen>
		<cid>1</cid>
		<name>Mingos</name>
		<place>Block1</place>
		<custid>1</custid>
		<stallid>1</stallid>
		<inputid>3</inputid>
	</canteen>
	<canteen>
		<cid>1</cid>
		<name>Mingos</name>
		<place>Block1</place>
		<custid>2</custid>
		<stallid>null</stallid>
		<inputid>3</inputid>
	</canteen>
	<canteen>
		<cid>1</cid>
		<name>Mingos</name>
		<place>Block1</place>
		<custid>2</custid>
		<stallid>1</stallid>
		<inputid>4</inputid>
	</canteen>
</canteenman>
